import type { Scheme } from '@/types';

/**
 * MITRA scheme catalogue — 18 real Government of India schemes.
 *
 * Eligibility criteria below are simplified, machine-evaluable approximations of the
 * published rules, sufficient for advisory matching. They are deliberately NOT
 * authoritative: the UI always frames results as "verify before you rely on this".
 * Income thresholds and age bands follow the widely published central guidelines;
 * state variants are out of scope for this catalogue.
 */
export const SCHEMES: Scheme[] = [
  {
    id: 'pm-kisan',
    name: 'Pradhan Mantri Kisan Samman Nidhi',
    shortName: 'PM-KISAN',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    sector: 'agriculture',
    level: 'central',
    tagline: 'Income support for landholding farmer families',
    summary:
      'If your family owns cultivable land, the government sends money straight to your bank account three times a year. You do not have to buy anything or show bills — it is direct income support to help with seeds, fertiliser and daily farm costs.',
    benefitHeadline: '₹6,000 per year',
    benefitDetail: 'Paid in three equal instalments of ₹2,000 directly into the beneficiary bank account.',
    rules: [
      { field: 'occupation', op: 'eq', value: 'farmer', label: 'You are a farmer with cultivable land' },
      { field: 'landHoldingHectares', op: 'exists', label: 'Land ownership record exists in your name' },
      { field: 'annualIncome', op: 'lte', value: 800000, label: 'Not an income-tax payer in the last assessment year', soft: true },
      { field: 'age', op: 'gte', value: 18, label: 'You are 18 or older' },
    ],
    documents: [
      { id: 'aadhaar', name: 'Aadhaar card' },
      { id: 'land-record', name: 'Land ownership record (Khasra / Khatauni)' },
      { id: 'bank-passbook', name: 'Bank passbook linked to Aadhaar' },
      { id: 'citizenship', name: 'Proof of citizenship', requiredIf: { field: 'area', op: 'eq', value: 'rural', label: 'Rural applicants' } },
    ],
    applyMode: ['PM-KISAN portal', 'Common Service Centre', 'Village revenue officer'],
    processingDays: 30,
    officialUrl: 'https://pmkisan.gov.in',
    relatedLifeEvents: ['farming-season'],
    icon: 'Sprout',
    accent: 'green',
  },
  {
    id: 'ayushman-bharat',
    name: 'Ayushman Bharat Pradhan Mantri Jan Arogya Yojana',
    shortName: 'Ayushman Bharat PM-JAY',
    ministry: 'Ministry of Health & Family Welfare',
    sector: 'health',
    level: 'central',
    tagline: 'Cashless hospital treatment for low-income families',
    summary:
      'Your family gets a health cover of ₹5 lakh every year. If someone falls seriously ill, you can go to any empanelled hospital — government or private — and the treatment is cashless. You do not pay first and claim later.',
    benefitHeadline: 'Up to ₹5 lakh per family per year',
    benefitDetail: 'Covers hospitalisation, surgery, medicines, diagnostics and 15 days of post-hospitalisation care at empanelled hospitals.',
    rules: [
      { field: 'annualIncome', op: 'lte', value: 300000, label: 'Household falls in the deprivation categories of the SECC database' },
      { field: 'familySize', op: 'gte', value: 1, label: 'Applies to the whole family with no cap on size' },
      { field: 'existingBenefits', op: 'excludes', value: 'esic', label: 'Not already covered by ESIC or CGHS', soft: true },
    ],
    documents: [
      { id: 'aadhaar', name: 'Aadhaar card' },
      { id: 'ration-card', name: 'Ration card' },
      { id: 'income-cert', name: 'Income certificate', validityMonths: 12 },
      { id: 'family-id', name: 'Family identity proof' },
    ],
    applyMode: ['Ayushman app', 'Common Service Centre', 'Empanelled hospital help desk'],
    processingDays: 15,
    officialUrl: 'https://pmjay.gov.in',
    relatedLifeEvents: ['childbirth', 'disability', 'senior-citizen'],
    icon: 'HeartPulse',
    accent: 'rose',
  },
  {
    id: 'pmay-urban',
    name: 'Pradhan Mantri Awas Yojana (Urban)',
    shortName: 'PM Awas Yojana (Urban)',
    ministry: 'Ministry of Housing & Urban Affairs',
    sector: 'housing',
    level: 'central',
    tagline: 'Affordable housing and home-loan interest subsidy',
    summary:
      'If you do not own a pucca house anywhere in India, this scheme helps you build or buy one. You get a subsidy on your home-loan interest, which lowers your monthly instalment for the whole loan period.',
    benefitHeadline: 'Interest subsidy up to ₹2.67 lakh',
    benefitDetail: 'Credit-linked subsidy on home loans, with the exact amount depending on your income group (EWS, LIG or MIG).',
    rules: [
      { field: 'area', op: 'eq', value: 'urban', label: 'You live in a notified urban area' },
      { field: 'annualIncome', op: 'lte', value: 1800000, label: 'Household income within the EWS / LIG / MIG limits' },
      { field: 'existingBenefits', op: 'excludes', value: 'pmay', label: 'No family member owns a pucca house or has taken this benefit before' },
      { field: 'age', op: 'gte', value: 21, label: 'You are 21 or older' },
    ],
    documents: [
      { id: 'aadhaar', name: 'Aadhaar of all family members' },
      { id: 'income-cert', name: 'Income certificate', validityMonths: 12 },
      { id: 'property-docs', name: 'Property or plot documents' },
      { id: 'bank-passbook', name: 'Bank account details' },
      { id: 'affidavit', name: 'Affidavit of no pucca house owned' },
    ],
    applyMode: ['PMAY-U portal', 'Common Service Centre', 'Urban local body office'],
    processingDays: 60,
    officialUrl: 'https://pmay-urban.gov.in',
    relatedLifeEvents: ['marriage', 'bought-home'],
    icon: 'Home',
    accent: 'amber',
  },
  {
    id: 'pmay-gramin',
    name: 'Pradhan Mantri Awas Yojana (Gramin)',
    shortName: 'PM Awas Yojana (Gramin)',
    ministry: 'Ministry of Rural Development',
    sector: 'housing',
    level: 'central',
    tagline: 'Assistance to build a pucca house in rural areas',
    summary:
      'For families in villages living in kutcha houses. The government gives you money in instalments to build a permanent house with a toilet, electricity and a cooking area.',
    benefitHeadline: '₹1.20 lakh – ₹1.30 lakh assistance',
    benefitDetail: 'Higher assistance for hilly, difficult and Left Wing Extremism affected districts, plus support under MGNREGA for labour.',
    rules: [
      { field: 'area', op: 'eq', value: 'rural', label: 'You live in a rural area' },
      { field: 'annualIncome', op: 'lte', value: 300000, label: 'Household is in the SECC deprivation list' },
      { field: 'existingBenefits', op: 'excludes', value: 'pmay', label: 'No pucca house owned by any family member' },
    ],
    documents: [
      { id: 'aadhaar', name: 'Aadhaar card' },
      { id: 'job-card', name: 'MGNREGA job card' },
      { id: 'bank-passbook', name: 'Bank passbook' },
      { id: 'swachh-id', name: 'Swachh Bharat Mission registration number' },
    ],
    applyMode: ['AwaasSoft portal', 'Gram Panchayat', 'Common Service Centre'],
    processingDays: 90,
    officialUrl: 'https://pmayg.nic.in',
    relatedLifeEvents: ['marriage', 'bought-home'],
    icon: 'HousePlus',
    accent: 'amber',
  },
  {
    id: 'post-matric-scholarship',
    name: 'Post Matric Scholarship for SC/ST/OBC Students',
    shortName: 'Post Matric Scholarship',
    ministry: 'Ministry of Social Justice & Empowerment',
    sector: 'education',
    level: 'central',
    tagline: 'Financial support for students after class 10',
    summary:
      'If you belong to SC, ST or OBC and are studying after class 10, this pays your course fees and gives you a monthly allowance so that money is not the reason you stop studying.',
    benefitHeadline: 'Full tuition + monthly allowance',
    benefitDetail: 'Covers course fees, maintenance allowance, study-tour charges, thesis typing and printing for eligible students.',
    rules: [
      { field: 'occupation', op: 'eq', value: 'student', label: 'You are currently enrolled in a post-matriculation course' },
      { field: 'category', op: 'in', value: ['sc', 'st', 'obc'], label: 'You belong to SC, ST or OBC category' },
      { field: 'annualIncome', op: 'lte', value: 250000, label: 'Family income within the prescribed limit' },
      { field: 'age', op: 'gte', value: 15, label: 'You have passed class 10' },
    ],
    documents: [
      { id: 'aadhaar', name: 'Aadhaar card' },
      { id: 'caste-cert', name: 'Caste certificate', validityMonths: 36 },
      { id: 'income-cert', name: 'Income certificate', validityMonths: 12 },
      { id: 'marksheet', name: 'Previous year marksheet' },
      { id: 'admission-proof', name: 'Institution admission or bonafide certificate' },
      { id: 'bank-passbook', name: 'Bank passbook in the student name' },
    ],
    applyMode: ['National Scholarship Portal', 'Institution scholarship cell'],
    processingDays: 45,
    officialUrl: 'https://scholarships.gov.in',
    relatedLifeEvents: ['started-studies'],
    icon: 'GraduationCap',
    accent: 'blue',
  },
  {
    id: 'pre-matric-scholarship',
    name: 'Pre Matric Scholarship for SC/ST Students',
    shortName: 'Pre Matric Scholarship',
    ministry: 'Ministry of Social Justice & Empowerment',
    sector: 'education',
    level: 'central',
    tagline: 'School support for classes 9 and 10',
    summary:
      'Helps SC and ST families keep children in school through classes 9 and 10 by covering books, uniforms and a monthly allowance.',
    benefitHeadline: '₹3,500 – ₹7,000 per year',
    benefitDetail: 'Monthly stipend plus an annual books-and-ad-hoc grant, with higher rates for hostellers.',
    rules: [
      { field: 'occupation', op: 'eq', value: 'student', label: 'You are studying in class 9 or 10' },
      { field: 'category', op: 'in', value: ['sc', 'st'], label: 'You belong to SC or ST category' },
      { field: 'annualIncome', op: 'lte', value: 250000, label: 'Parent or guardian income within the limit' },
      { field: 'age', op: 'lte', value: 20, label: 'Within the prescribed age band for school students' },
    ],
    documents: [
      { id: 'aadhaar', name: 'Aadhaar card' },
      { id: 'caste-cert', name: 'Caste certificate', validityMonths: 36 },
      { id: 'income-cert', name: 'Income certificate', validityMonths: 12 },
      { id: 'school-cert', name: 'School bonafide certificate' },
    ],
    applyMode: ['National Scholarship Portal', 'School office'],
    processingDays: 45,
    officialUrl: 'https://scholarships.gov.in',
    relatedLifeEvents: ['started-studies'],
    icon: 'BookOpen',
    accent: 'blue',
  },
  {
    id: 'pm-vishwakarma',
    name: 'PM Vishwakarma Yojana',
    shortName: 'PM Vishwakarma',
    ministry: 'Ministry of Micro, Small & Medium Enterprises',
    sector: 'business',
    level: 'central',
    tagline: 'Support for traditional artisans and craftspeople',
    summary:
      'For people who work with their hands — carpenters, potters, blacksmiths, tailors, barbers and other traditional trades. You get skill training with a daily stipend, money to buy tools, and a small loan at a low interest rate.',
    benefitHeadline: '₹15,000 toolkit + loans up to ₹3 lakh',
    benefitDetail: 'Free skill training with ₹500 daily stipend, a ₹15,000 toolkit grant, and collateral-free credit at 5% interest in two tranches.',
    rules: [
      { field: 'occupation', op: 'in', value: ['artisan', 'self-employed'], label: 'You work in one of the 18 recognised traditional trades' },
      { field: 'age', op: 'gte', value: 18, label: 'You are 18 or older' },
      { field: 'existingBenefits', op: 'excludes', value: 'pmegp', label: 'Have not taken a similar credit-linked benefit under PMEGP or Mudra recently', soft: true },
    ],
    documents: [
      { id: 'aadhaar', name: 'Aadhaar card' },
      { id: 'bank-passbook', name: 'Bank account details' },
      { id: 'ration-card', name: 'Ration card' },
      { id: 'trade-proof', name: 'Proof of practising the trade' },
    ],
    applyMode: ['PM Vishwakarma portal', 'Common Service Centre'],
    processingDays: 45,
    officialUrl: 'https://pmvishwakarma.gov.in',
    relatedLifeEvents: ['started-business', 'job-loss'],
    icon: 'Hammer',
    accent: 'violet',
  },
  {
    id: 'mudra-loan',
    name: 'Pradhan Mantri Mudra Yojana',
    shortName: 'Mudra Loan',
    ministry: 'Ministry of Finance',
    sector: 'business',
    level: 'central',
    tagline: 'Collateral-free loans for small businesses',
    summary:
      'If you run or want to start a small business — a shop, a workshop, a service — you can get a loan without giving any property as security. There are three sizes depending on how big your need is.',
    benefitHeadline: 'Loans up to ₹10 lakh',
    benefitDetail: 'Shishu up to ₹50,000, Kishore ₹50,000–₹5 lakh, Tarun ₹5–10 lakh, all without collateral.',
    rules: [
      { field: 'occupation', op: 'in', value: ['self-employed', 'artisan', 'unemployed'], label: 'You run or plan to start a non-farm micro enterprise' },
      { field: 'age', op: 'gte', value: 18, label: 'You are 18 or older' },
      { field: 'age', op: 'lte', value: 65, label: 'You are 65 or younger' },
    ],
    documents: [
      { id: 'aadhaar', name: 'Aadhaar card' },
      { id: 'pan', name: 'PAN card' },
      { id: 'business-plan', name: 'Business plan or quotation' },
      { id: 'bank-statement', name: 'Six months bank statement' },
      { id: 'address-proof', name: 'Business address proof' },
    ],
    applyMode: ['Any scheduled bank', 'Udyamimitra portal', 'Common Service Centre'],
    processingDays: 21,
    officialUrl: 'https://www.mudra.org.in',
    relatedLifeEvents: ['started-business', 'job-loss'],
    icon: 'Briefcase',
    accent: 'violet',
  },
  {
    id: 'nsap-old-age',
    name: 'Indira Gandhi National Old Age Pension Scheme',
    shortName: 'Old Age Pension (IGNOAPS)',
    ministry: 'Ministry of Rural Development',
    sector: 'pension',
    level: 'central',
    tagline: 'Monthly pension for elderly citizens below poverty line',
    summary:
      'If you are 60 or above and your family is on the BPL list, you get a monthly pension in your bank account so you are not dependent on anyone for basic needs.',
    benefitHeadline: '₹200 – ₹500 per month',
    benefitDetail: '₹200 monthly for ages 60–79 and ₹500 from age 80, usually topped up by an additional state contribution.',
    rules: [
      { field: 'age', op: 'gte', value: 60, label: 'You are 60 years or older' },
      { field: 'annualIncome', op: 'lte', value: 120000, label: 'Household is on the Below Poverty Line list' },
      { field: 'existingBenefits', op: 'excludes', value: 'govt-pension', label: 'Not drawing any other government service pension' },
    ],
    documents: [
      { id: 'aadhaar', name: 'Aadhaar card' },
      { id: 'age-proof', name: 'Age proof' },
      { id: 'bpl-card', name: 'BPL ration card' },
      { id: 'bank-passbook', name: 'Bank passbook' },
    ],
    applyMode: ['Gram Panchayat', 'Block Development Office', 'Common Service Centre'],
    processingDays: 45,
    officialUrl: 'https://nsap.nic.in',
    relatedLifeEvents: ['senior-citizen'],
    icon: 'UserRound',
    accent: 'teal',
  },
  {
    id: 'nsap-widow',
    name: 'Indira Gandhi National Widow Pension Scheme',
    shortName: 'Widow Pension (IGNWPS)',
    ministry: 'Ministry of Rural Development',
    sector: 'pension',
    level: 'central',
    tagline: 'Monthly pension for widows from BPL households',
    summary:
      'A monthly pension for women who have lost their husband and belong to a below-poverty-line household, paid directly into their own bank account.',
    benefitHeadline: '₹300 – ₹500 per month',
    benefitDetail: '₹300 monthly for ages 40–79 and ₹500 from age 80, commonly supplemented by the state.',
    rules: [
      { field: 'gender', op: 'eq', value: 'female', label: 'Applicant is a woman' },
      { field: 'age', op: 'gte', value: 40, label: 'You are 40 years or older' },
      { field: 'annualIncome', op: 'lte', value: 120000, label: 'Household is on the Below Poverty Line list' },
      { field: 'lifeEvents', op: 'includes', value: 'bereavement', label: 'Widowed, with a death certificate for the spouse' },
    ],
    documents: [
      { id: 'aadhaar', name: 'Aadhaar card' },
      { id: 'death-cert', name: 'Husband death certificate' },
      { id: 'bpl-card', name: 'BPL ration card' },
      { id: 'bank-passbook', name: 'Bank passbook' },
      { id: 'age-proof', name: 'Age proof' },
    ],
    applyMode: ['Gram Panchayat', 'Block Development Office', 'Common Service Centre'],
    processingDays: 45,
    officialUrl: 'https://nsap.nic.in',
    relatedLifeEvents: ['bereavement', 'senior-citizen'],
    icon: 'HeartHandshake',
    accent: 'teal',
  },
  {
    id: 'nsap-disability',
    name: 'Indira Gandhi National Disability Pension Scheme',
    shortName: 'Disability Pension (IGNDPS)',
    ministry: 'Ministry of Rural Development',
    sector: 'disability',
    level: 'central',
    tagline: 'Monthly pension for persons with severe disability',
    summary:
      'A monthly pension for people with 80% or more disability from below-poverty-line households, to cover ongoing care and living costs.',
    benefitHeadline: '₹300 – ₹500 per month',
    benefitDetail: '₹300 monthly for ages 18–79 and ₹500 from age 80, typically with an additional state top-up.',
    rules: [
      { field: 'hasDisability', op: 'eq', value: true, label: 'You have a certified disability' },
      { field: 'disabilityPercent', op: 'gte', value: 80, label: 'Disability assessed at 80% or above' },
      { field: 'age', op: 'gte', value: 18, label: 'You are 18 or older' },
      { field: 'annualIncome', op: 'lte', value: 120000, label: 'Household is on the Below Poverty Line list' },
    ],
    documents: [
      { id: 'aadhaar', name: 'Aadhaar card' },
      { id: 'disability-cert', name: 'Disability certificate (UDID)', validityMonths: 60 },
      { id: 'bpl-card', name: 'BPL ration card' },
      { id: 'bank-passbook', name: 'Bank passbook' },
    ],
    applyMode: ['Gram Panchayat', 'District Social Welfare Office', 'Common Service Centre'],
    processingDays: 45,
    officialUrl: 'https://nsap.nic.in',
    relatedLifeEvents: ['disability'],
    icon: 'Accessibility',
    accent: 'teal',
  },
  {
    id: 'sukanya-samriddhi',
    name: 'Sukanya Samriddhi Yojana',
    shortName: 'Sukanya Samriddhi',
    ministry: 'Ministry of Finance',
    sector: 'women-child',
    level: 'central',
    tagline: 'High-interest savings account for a girl child',
    summary:
      'Open a savings account for your daughter before she turns 10. It earns a higher interest rate than a normal bank account, and the money is tax free — meant for her education and marriage.',
    benefitHeadline: '8.2% annual interest, tax free',
    benefitDetail: 'Deposit ₹250 to ₹1.5 lakh a year for 15 years; the account matures when the girl turns 21, with partial withdrawal allowed at 18 for education.',
    rules: [
      { field: 'gender', op: 'eq', value: 'female', label: 'Account is for a girl child' },
      { field: 'age', op: 'lte', value: 10, label: 'The girl is under 10 years old' },
    ],
    documents: [
      { id: 'birth-cert', name: 'Birth certificate of the girl child' },
      { id: 'aadhaar', name: 'Aadhaar of parent or guardian' },
      { id: 'address-proof', name: 'Address proof' },
      { id: 'photo', name: 'Passport-size photographs' },
    ],
    applyMode: ['Any post office', 'Authorised bank branch'],
    processingDays: 7,
    officialUrl: 'https://www.indiapost.gov.in',
    relatedLifeEvents: ['childbirth'],
    icon: 'PiggyBank',
    accent: 'rose',
  },
  {
    id: 'janani-suraksha',
    name: 'Janani Suraksha Yojana',
    shortName: 'Janani Suraksha Yojana',
    ministry: 'Ministry of Health & Family Welfare',
    sector: 'women-child',
    level: 'central',
    tagline: 'Cash assistance for safe institutional delivery',
    summary:
      'Encourages mothers to deliver in a hospital instead of at home. You get cash assistance after delivery, and an ASHA worker helps you through check-ups and transport.',
    benefitHeadline: '₹1,400 rural / ₹1,000 urban',
    benefitDetail: 'Cash assistance to the mother after institutional delivery, plus a performance incentive for the accompanying ASHA worker.',
    rules: [
      { field: 'gender', op: 'eq', value: 'female', label: 'Applicant is a pregnant woman or new mother' },
      { field: 'age', op: 'gte', value: 19, label: 'Aged 19 or above for the general category', soft: true },
      { field: 'lifeEvents', op: 'includes', value: 'childbirth', label: 'Currently pregnant or recently delivered' },
      { field: 'annualIncome', op: 'lte', value: 300000, label: 'From a BPL household in high-performing states', soft: true },
    ],
    documents: [
      { id: 'aadhaar', name: 'Aadhaar card' },
      { id: 'mcp-card', name: 'Mother and Child Protection card' },
      { id: 'bank-passbook', name: 'Bank passbook' },
      { id: 'bpl-card', name: 'BPL certificate', requiredIf: { field: 'area', op: 'eq', value: 'urban', label: 'Urban applicants' } },
    ],
    applyMode: ['Government hospital', 'ASHA worker', 'Primary Health Centre'],
    processingDays: 14,
    officialUrl: 'https://nhm.gov.in',
    relatedLifeEvents: ['childbirth'],
    icon: 'Baby',
    accent: 'rose',
  },
  {
    id: 'pmsby',
    name: 'Pradhan Mantri Suraksha Bima Yojana',
    shortName: 'PM Suraksha Bima',
    ministry: 'Ministry of Finance',
    sector: 'financial',
    level: 'central',
    tagline: 'Accident insurance for ₹20 a year',
    summary:
      'For twenty rupees a year, auto-debited from your bank account, your family gets ₹2 lakh if you die in an accident, or you get money if an accident leaves you disabled.',
    benefitHeadline: '₹2 lakh cover for ₹20/year',
    benefitDetail: '₹2 lakh for accidental death or total permanent disability, ₹1 lakh for partial permanent disability.',
    rules: [
      { field: 'age', op: 'gte', value: 18, label: 'You are 18 or older' },
      { field: 'age', op: 'lte', value: 70, label: 'You are 70 or younger' },
    ],
    documents: [
      { id: 'aadhaar', name: 'Aadhaar card' },
      { id: 'bank-passbook', name: 'Savings bank account with auto-debit consent' },
      { id: 'nominee', name: 'Nominee details' },
    ],
    applyMode: ['Your bank branch', 'Net banking', 'Common Service Centre'],
    processingDays: 3,
    officialUrl: 'https://www.jansuraksha.gov.in',
    relatedLifeEvents: ['job-loss', 'started-business'],
    icon: 'ShieldCheck',
    accent: 'blue',
  },
  {
    id: 'pmjjby',
    name: 'Pradhan Mantri Jeevan Jyoti Bima Yojana',
    shortName: 'PM Jeevan Jyoti Bima',
    ministry: 'Ministry of Finance',
    sector: 'financial',
    level: 'central',
    tagline: 'Life insurance for ₹436 a year',
    summary:
      'A simple life insurance cover. If you pass away for any reason while the policy is active, your family receives ₹2 lakh. The premium is taken from your bank account once a year.',
    benefitHeadline: '₹2 lakh life cover',
    benefitDetail: 'One-year renewable term life cover of ₹2 lakh at a premium of ₹436 per year, auto-debited annually.',
    rules: [
      { field: 'age', op: 'gte', value: 18, label: 'You are 18 or older' },
      { field: 'age', op: 'lte', value: 50, label: 'You are 50 or younger at entry' },
    ],
    documents: [
      { id: 'aadhaar', name: 'Aadhaar card' },
      { id: 'bank-passbook', name: 'Savings bank account with auto-debit consent' },
      { id: 'nominee', name: 'Nominee details' },
      { id: 'health-declaration', name: 'Self-declaration of good health' },
    ],
    applyMode: ['Your bank branch', 'Net banking', 'Common Service Centre'],
    processingDays: 3,
    officialUrl: 'https://www.jansuraksha.gov.in',
    relatedLifeEvents: ['marriage', 'childbirth'],
    icon: 'Shield',
    accent: 'blue',
  },
  {
    id: 'atal-pension',
    name: 'Atal Pension Yojana',
    shortName: 'Atal Pension Yojana',
    ministry: 'Ministry of Finance',
    sector: 'pension',
    level: 'central',
    tagline: 'Guaranteed pension after 60 for unorganised workers',
    summary:
      'You pay a small amount every month while you are working. After you turn 60, the government pays you a fixed pension every month for life, and your spouse continues to receive it after you.',
    benefitHeadline: '₹1,000 – ₹5,000 monthly after 60',
    benefitDetail: 'Guaranteed monthly pension from age 60, with the same amount to the spouse thereafter and the corpus returned to nominees.',
    rules: [
      { field: 'age', op: 'gte', value: 18, label: 'You are 18 or older' },
      { field: 'age', op: 'lte', value: 40, label: 'You are 40 or younger at the time of joining' },
      { field: 'occupation', op: 'nin', value: ['retired'], label: 'You are in the working-age unorganised sector' },
      { field: 'annualIncome', op: 'lte', value: 800000, label: 'Not an income-tax payer', soft: true },
    ],
    documents: [
      { id: 'aadhaar', name: 'Aadhaar card' },
      { id: 'bank-passbook', name: 'Savings bank account' },
      { id: 'mobile', name: 'Mobile number linked to the account' },
      { id: 'nominee', name: 'Nominee details' },
    ],
    applyMode: ['Your bank branch', 'Net banking', 'Post office'],
    processingDays: 7,
    officialUrl: 'https://www.npscra.nsdl.co.in',
    relatedLifeEvents: ['started-business', 'job-loss'],
    icon: 'Landmark',
    accent: 'teal',
  },
  {
    id: 'e-shram',
    name: 'e-Shram National Database of Unorganised Workers',
    shortName: 'e-Shram Card',
    ministry: 'Ministry of Labour & Employment',
    sector: 'employment',
    level: 'central',
    tagline: 'Universal ID and accident cover for unorganised workers',
    summary:
      'If you work as a labourer, street vendor, domestic worker, driver or in any job without a formal contract, register once and get a card. It brings free accident insurance and makes you visible for future welfare schemes.',
    benefitHeadline: 'Free ₹2 lakh accident cover',
    benefitDetail: 'A Universal Account Number card, ₹2 lakh accidental death and disability cover for the first year, and priority access to future welfare schemes.',
    rules: [
      { field: 'age', op: 'gte', value: 16, label: 'You are 16 or older' },
      { field: 'age', op: 'lte', value: 59, label: 'You are 59 or younger' },
      { field: 'occupation', op: 'in', value: ['daily-wage', 'self-employed', 'artisan', 'farmer', 'homemaker', 'unemployed'], label: 'You work in the unorganised sector' },
      { field: 'existingBenefits', op: 'excludes', value: 'epfo', label: 'Not a member of EPFO or ESIC' },
    ],
    documents: [
      { id: 'aadhaar', name: 'Aadhaar card with linked mobile number' },
      { id: 'bank-passbook', name: 'Bank account details' },
    ],
    applyMode: ['e-Shram portal', 'Common Service Centre', 'State Seva Kendra'],
    processingDays: 1,
    officialUrl: 'https://eshram.gov.in',
    relatedLifeEvents: ['job-loss', 'started-business'],
    icon: 'IdCard',
    accent: 'green',
  },
  {
    id: 'pmegp',
    name: 'Prime Minister Employment Generation Programme',
    shortName: 'PMEGP',
    ministry: 'Ministry of Micro, Small & Medium Enterprises',
    sector: 'employment',
    level: 'central',
    tagline: 'Subsidy to set up your own manufacturing or service unit',
    summary:
      'If you want to start your own small manufacturing or service unit, the government pays a large part of the project cost as a subsidy. You only need to bring a small share of your own money.',
    benefitHeadline: '15–35% government subsidy',
    benefitDetail: 'Projects up to ₹50 lakh in manufacturing and ₹20 lakh in services, with a higher subsidy rate for rural areas and special categories.',
    rules: [
      { field: 'age', op: 'gte', value: 18, label: 'You are 18 or older' },
      { field: 'occupation', op: 'in', value: ['unemployed', 'self-employed', 'artisan'], label: 'You are setting up a new enterprise' },
      { field: 'existingBenefits', op: 'excludes', value: 'pmegp', label: 'Have not availed PMEGP subsidy before' },
    ],
    documents: [
      { id: 'aadhaar', name: 'Aadhaar card' },
      { id: 'pan', name: 'PAN card' },
      { id: 'project-report', name: 'Detailed project report' },
      { id: 'education-cert', name: 'Education certificate', requiredIf: { field: 'annualIncome', op: 'gte', value: 1000000, label: 'Projects above ₹10 lakh' } },
      { id: 'caste-cert', name: 'Caste certificate for subsidy enhancement', requiredIf: { field: 'category', op: 'in', value: ['sc', 'st', 'obc'], label: 'Reserved category applicants' } },
    ],
    applyMode: ['PMEGP e-portal', 'District Industries Centre', 'KVIC office'],
    processingDays: 60,
    officialUrl: 'https://www.kviconline.gov.in/pmegpeportal',
    relatedLifeEvents: ['started-business', 'job-loss'],
    icon: 'Factory',
    accent: 'violet',
  },
];

export const getScheme = (id: string): Scheme | undefined => SCHEMES.find((s) => s.id === id);

export const SECTOR_LABELS: Record<string, string> = {
  agriculture: 'Agriculture',
  health: 'Health',
  education: 'Education',
  housing: 'Housing',
  pension: 'Pension',
  employment: 'Employment',
  business: 'Business',
  'women-child': 'Women & Child',
  disability: 'Disability',
  financial: 'Insurance & Savings',
};
